/* Fuente de datos: PokéAPI REST v2 (https://pokeapi.co/docs/v2).
   PokéAPI no publica episodios del anime; por eso no se inventa esa información. */
const API = 'https://pokeapi.co/api/v2';
const PAGE_SIZE = 48;
const SUGGESTION_LIMIT = 8;
const typeNames = {normal:'Normal',fighting:'Lucha',flying:'Volador',poison:'Veneno',ground:'Tierra',rock:'Roca',bug:'Bicho',ghost:'Fantasma',steel:'Acero',fire:'Fuego',water:'Agua',grass:'Planta',electric:'Eléctrico',psychic:'Psíquico',ice:'Hielo',dragon:'Dragón',dark:'Siniestro',fairy:'Hada'};
const FALLBACK_IMAGE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 160 160'%3E%3Crect width='160' height='160' rx='18' fill='%23edf1f6'/%3E%3Ccircle cx='80' cy='80' r='39' fill='%23e63946'/%3E%3Cpath d='M41 80h78' stroke='white' stroke-width='10'/%3E%3Ccircle cx='80' cy='80' r='12' fill='white' stroke='%23243246' stroke-width='7'/%3E%3C/svg%3E";
const state = {catalog:[],filtered:[],byName:new Map(),byId:new Map(),selectedTypes:new Set(),page:1,pokemonCache:new Map(),speciesCache:new Map(),abilityCache:new Map(),typeCache:new Map(),catalogVersion:0,filterVersion:0,detailVersion:0,loadingCount:0};
const $ = id => document.getElementById(id);
const ui = {form:$('search-form'),input:$('search-input'),suggestions:$('suggestions'),notice:$('notice'),loading:$('loading'),loadingText:$('loading-text'),detail:$('detail'),types:$('type-filters'),catalog:$('catalog'),count:$('catalog-count'),page:$('page-label'),prev:$('prev-page'),next:$('next-page')};

function startLoading(text = 'Cargando Pokémon…') { state.loadingCount += 1; ui.loadingText.textContent = text; ui.loading.classList.add('visible'); let done = false; return () => { if (done) return; done = true; state.loadingCount = Math.max(0, state.loadingCount - 1); if (!state.loadingCount) ui.loading.classList.remove('visible'); }; }
function showNotice(message, error = false) { ui.notice.textContent = message; ui.notice.className = `notice visible${error ? ' error' : ''}`; }
function clearNotice() { ui.notice.className = 'notice'; ui.notice.textContent = ''; }
function displayName(name = '') { return name.replaceAll('-', ' '); }
function getId(entry) { return Number(entry.url.match(/\/(\d+)\/$/)?.[1]) || 0; }
function normalizeIdentifier(value) { const text = value.trim().toLowerCase().replace(/^(#|n[ºo.]?\s*)/i, ''); return /^\d+$/.test(text) ? String(Number(text)) : text; }
function sprite(pokemon) { return pokemon.sprites?.other?.['official-artwork']?.front_default || pokemon.sprites?.other?.home?.front_default || pokemon.sprites?.front_default || FALLBACK_IMAGE; }
function spanishText(entries = []) { return entries.find(e => e.language.name === 'es')?.flavor_text?.replace(/[\n\f]/g, ' ') || entries.find(e => e.language.name === 'en')?.flavor_text?.replace(/[\n\f]/g, ' ') || 'Sin descripción disponible.'; }
function typeChips(types = []) { return types.map(t => `<span class="chip">${typeNames[t.type?.name || t] || (t.type?.name || t)}</span>`).join(''); }

function wait(milliseconds) { return new Promise(resolve => setTimeout(resolve, milliseconds)); }
async function api(path, attempt = 0) { try { const response = await fetch(`${API}${path}`); if (!response.ok) { const error = new Error(response.status === 404 ? 'not-found' : 'api-error'); error.retryable = response.status === 429 || response.status >= 500; throw error; } return await response.json(); } catch (error) { const retryable = error.retryable || error.name === 'TypeError'; if (retryable && attempt < 2) { await wait(350 * (attempt + 1)); return api(path, attempt + 1); } throw error; } }
async function cached(cache, key, loader) { if (!cache.has(key)) { const request = loader().catch(error => { cache.delete(key); throw error; }); cache.set(key, request); } return cache.get(key); }
async function fetchPokemon(identifier) { const key = normalizeIdentifier(String(identifier)); const data = await cached(state.pokemonCache, key, () => api(`/pokemon/${encodeURIComponent(key)}`)); state.pokemonCache.set(data.name, data); state.pokemonCache.set(String(data.id), data); return data; }
async function fetchPokemonSpecies(identifier) { const key = String(identifier).toLowerCase(); const data = await cached(state.speciesCache, key, () => api(`/pokemon-species/${encodeURIComponent(key)}`)); state.speciesCache.set(data.name, data); return data; }
async function fetchAbility(name) { return cached(state.abilityCache, name, () => api(`/ability/${encodeURIComponent(name)}`)); }
async function fetchType(name) { return cached(state.typeCache, name, () => api(`/type/${encodeURIComponent(name)}`)); }
async function fetchPokemonCatalog() { const data = await api('/pokemon?limit=100000&offset=0'); return data.results; }
async function fetchTypes() { const data = await api('/type'); return data.results.filter(item => typeNames[item.name]); }

function renderFilters(types) { ui.types.innerHTML = types.map(type => `<button class="type-filter" type="button" data-type="${type.name}" aria-pressed="false">${typeNames[type.name]}</button>`).join(''); }
function hideSuggestions() { ui.suggestions.classList.remove('show'); ui.suggestions.innerHTML = ''; ui.input.setAttribute('aria-expanded', 'false'); }
function renderSuggestions(rawQuery) { const query = normalizeIdentifier(rawQuery); if (!query || !state.catalog.length) return hideSuggestions(); let matches = []; if (/^\d+$/.test(query)) { const exact = state.byId.get(Number(query)); if (exact) matches = [exact]; } else matches = state.catalog.filter(entry => entry.name.includes(query)).slice(0, SUGGESTION_LIMIT); ui.suggestions.innerHTML = matches.map(entry => `<button class="suggestion" type="button" role="option" data-pokemon="${entry.name}"><span class="suggestion-id">N.º ${String(getId(entry)).padStart(4,'0')}</span><span class="suggestion-name">${displayName(entry.name)}</span></button>`).join(''); ui.suggestions.classList.toggle('show', matches.length > 0); ui.input.setAttribute('aria-expanded', String(matches.length > 0)); }
function currentSuggestions() { return [...ui.suggestions.querySelectorAll('[data-pokemon]')]; }

async function applyFilters() { const version = ++state.filterVersion; const selected = [...state.selectedTypes]; let filtered = state.catalog; if (selected.length) { const typeData = await Promise.all(selected.map(fetchType)); const sets = typeData.map(data => new Set(data.pokemon.map(item => item.pokemon.name))); filtered = state.catalog.filter(item => sets.every(set => set.has(item.name))); } if (version !== state.filterVersion) return; state.filtered = filtered; state.page = 1; renderCatalog(); }
async function loadCards(entries) { const cards = []; let failures = 0; for (let index = 0; index < entries.length; index += 6) { const batch = await Promise.allSettled(entries.slice(index, index + 6).map(entry => fetchPokemon(entry.name))); batch.forEach(result => result.status === 'fulfilled' ? cards.push(result.value) : failures += 1); if (index + 6 < entries.length) await wait(80); } return {cards, failures}; }
async function renderCatalog() { const version = ++state.catalogVersion; const total = state.filtered.length, totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE)); state.page = Math.max(1, Math.min(state.page, totalPages)); ui.count.textContent = `${total.toLocaleString('es-CO')} resultado${total === 1 ? '' : 's'}`; ui.page.textContent = `Página ${state.page} de ${totalPages}`; ui.prev.disabled = state.page <= 1; ui.next.disabled = state.page >= totalPages; const entries = state.filtered.slice((state.page - 1) * PAGE_SIZE, state.page * PAGE_SIZE); if (!entries.length) { ui.catalog.innerHTML = '<p class="empty">No hay Pokémon que cumplan esos tipos.</p>'; return; } ui.catalog.innerHTML = '<p class="empty">Cargando tarjetas…</p>'; try { const {cards, failures} = await loadCards(entries); if (version !== state.catalogVersion) return; if (!cards.length) throw new Error('catalog-unavailable'); ui.catalog.innerHTML = cards.map(cardTemplate).join(''); if (failures) showNotice(`Mostramos ${cards.length} tarjetas; algunas no pudieron cargarse todavía. Puedes cambiar de página o intentarlo de nuevo.`, false); } catch { if (version === state.catalogVersion) ui.catalog.innerHTML = '<p class="empty">PokéAPI no respondió para estas tarjetas.<br><button class="primary" type="button" data-retry-catalog>Reintentar</button></p>'; } }
function cardTemplate(pokemon) { return `<button class="card" type="button" data-pokemon="${pokemon.name}"><img src="${sprite(pokemon)}" alt="${displayName(pokemon.name)}"><span class="card-no">N.º ${String(pokemon.id).padStart(4,'0')}</span><span class="card-name">${displayName(pokemon.name)}</span><span class="chips">${typeChips(pokemon.types)}</span></button>`; }

function evolutionCondition(details) { const d = details?.[0]; if (!d) return ''; const bits = []; if (d.min_level) bits.push(`Nivel ${d.min_level}`); if (d.min_happiness) bits.push('Amistad'); if (d.item) bits.push(`Objeto: ${displayName(d.item.name)}`); if (d.held_item) bits.push(`Con ${displayName(d.held_item.name)}`); if (d.trigger?.name === 'trade') bits.push('Intercambio'); if (d.trigger?.name === 'use-item' && !d.item) bits.push('Usar objeto'); if (d.time_of_day) bits.push(d.time_of_day === 'day' ? 'De día' : 'De noche'); return bits.join(' · '); }
async function evolutionNode(node, currentName) { const pokemon = await fetchPokemon(node.species.name); const preview = `<span class="evo-tooltip"><b>N.º ${String(pokemon.id).padStart(4,'0')} · ${displayName(pokemon.name)}</b><span class="chips">${typeChips(pokemon.types)}</span><span>Peso: ${(pokemon.weight / 10).toLocaleString('es-CO')} kg<br>Altura: ${(pokemon.height / 10).toLocaleString('es-CO')} m</span><br><em>Haz clic para abrir su ficha</em></span>`; const own = `<button class="evo ${node.species.name === currentName ? 'current' : ''}" type="button" data-pokemon="${pokemon.name}" aria-label="Abrir ficha de ${displayName(pokemon.name)}"><img src="${sprite(pokemon)}" alt=""><span>${displayName(node.species.name)}</span>${node.species.name === currentName ? '<small>Actual</small>' : ''}${preview}</button>`; if (!node.evolves_to.length) return own; const children = await Promise.all(node.evolves_to.map(child => evolutionNode(child, currentName))); return `${own}${children.map((child, index) => `<span class="arrow">→</span><div class="branch"><span class="muted">${evolutionCondition(node.evolves_to[index].evolution_details)}</span>${child}</div>`).join('')}`; }
async function renderPokemon(identifier) { const version = ++state.detailVersion; clearNotice(); hideSuggestions(); const finishLoading = startLoading('Consultando datos y evolución…'); try { const pokemon = await fetchPokemon(identifier); const species = await fetchPokemonSpecies(pokemon.species.name); const abilityRecords = await Promise.all(pokemon.abilities.map(async entry => ({entry, data:await fetchAbility(entry.ability.name)}))); const evolution = await api(species.evolution_chain.url.replace(API, '')); const evoHtml = await evolutionNode(evolution.chain, pokemon.name); if (version !== state.detailVersion) return; const speciesName = species.genera.find(g => g.language.name === 'es')?.genus || species.genera.find(g => g.language.name === 'en')?.genus || 'Especie desconocida'; const lead = abilityRecords.find(item => !item.entry.is_hidden && item.entry.slot === 1) || abilityRecords[0]; const abilities = abilityRecords.map(({entry,data}) => `<div class="ability-item"><b>${displayName(entry.ability.name)}</b>${entry.is_hidden ? ' <span class="muted">(oculta)</span>' : ''}<div class="muted">${spanishText(data.flavor_text_entries)}</div></div>`).join(''); ui.detail.innerHTML = `<div class="detail-head"><img class="art" src="${sprite(pokemon)}" alt="${displayName(pokemon.name)}"><div><div class="eyebrow">N.º ${String(pokemon.id).padStart(4,'0')}</div><h2>${displayName(pokemon.name)}</h2><div class="chips">${typeChips(pokemon.types)}</div><div class="facts"><div class="fact"><strong>ESPECIE</strong>${speciesName}</div><div class="fact"><strong>PESO</strong>${(pokemon.weight / 10).toLocaleString('es-CO')} kg</div><div class="fact"><strong>ALTURA</strong>${(pokemon.height / 10).toLocaleString('es-CO')} m</div></div></div></div><div class="detail-sections"><article class="subpanel"><h3>Habilidad destacada</h3>${lead ? `<div class="ability-item"><b>${displayName(lead.entry.ability.name)}</b>${lead.entry.is_hidden ? ' <span class="muted">(oculta)</span>' : ''}<div class="muted">Se destaca por ser la habilidad principal registrada (slot ${lead.entry.slot}). ${spanishText(lead.data.flavor_text_entries)}</div></div>` : '<p class="muted">No hay habilidades disponibles.</p>'}<h3>Todas las habilidades</h3>${abilities}</article><article class="subpanel"><h3>Familia evolutiva</h3><div class="evolutions">${evoHtml}</div></article><article class="subpanel"><h3>Primera aparición en el anime</h3><p class="muted">Información del anime no disponible mediante PokéAPI.</p></article></div>`; ui.detail.classList.add('show'); if (window.innerWidth < 700) ui.detail.scrollIntoView({behavior:'smooth',block:'start'}); } catch (error) { if (version === state.detailVersion) showNotice(error.message === 'not-found' ? 'No encontramos ese Pokémon o ID. Intenta con otro nombre o número.' : 'No pudimos conectar con PokéAPI. Comprueba tu conexión e inténtalo de nuevo.', true); } finally { finishLoading(); } }
async function search(query) { const identifier = normalizeIdentifier(query); if (!identifier || identifier === '0') { showNotice('Escribe un nombre o un ID de Pokémon válido.', true); return; } const exact = state.byName.get(identifier) || state.byId.get(Number(identifier)); const firstSuggestion = currentSuggestions()[0]?.dataset.pokemon; await renderPokemon(exact?.name || firstSuggestion || identifier); }

function bindEvents() { document.addEventListener('error', event => { if (event.target.tagName === 'IMG' && event.target.src !== FALLBACK_IMAGE) { event.target.src = FALLBACK_IMAGE; event.target.alt = 'Imagen no disponible'; } }, true); ui.form.addEventListener('submit', event => { event.preventDefault(); search(ui.input.value); }); ui.input.addEventListener('input', () => { clearNotice(); renderSuggestions(ui.input.value); }); ui.input.addEventListener('keydown', event => { const items = currentSuggestions(); if (event.key === 'Escape') hideSuggestions(); if (event.key === 'ArrowDown' && items.length) { event.preventDefault(); items[0].focus(); } }); ui.suggestions.addEventListener('click', event => { const option = event.target.closest('[data-pokemon]'); if (option) { ui.input.value = option.dataset.pokemon; renderPokemon(option.dataset.pokemon); } }); document.addEventListener('click', event => { if (!event.target.closest('.search-wrap')) hideSuggestions(); }); ui.types.addEventListener('click', async event => { const button = event.target.closest('[data-type]'); if (!button) return; const name = button.dataset.type; state.selectedTypes.has(name) ? state.selectedTypes.delete(name) : state.selectedTypes.add(name); button.classList.toggle('selected'); button.setAttribute('aria-pressed', String(state.selectedTypes.has(name))); const finishLoading = startLoading('Aplicando filtros…'); try { await applyFilters(); } catch { showNotice('No se pudieron aplicar los filtros. Inténtalo de nuevo.', true); } finally { finishLoading(); } }); $('clear-filters').addEventListener('click', () => { state.filterVersion += 1; state.selectedTypes.clear(); document.querySelectorAll('.type-filter').forEach(button => { button.classList.remove('selected'); button.setAttribute('aria-pressed', 'false'); }); state.filtered = state.catalog; state.page = 1; renderCatalog(); }); ui.catalog.addEventListener('click', event => { if (event.target.closest('[data-retry-catalog]')) { renderCatalog(); return; } const card = event.target.closest('[data-pokemon]'); if (card) renderPokemon(card.dataset.pokemon); }); ui.detail.addEventListener('click', event => { const evolution = event.target.closest('button.evo[data-pokemon]'); if (evolution) renderPokemon(evolution.dataset.pokemon); }); const movePage = direction => { const pages = Math.max(1, Math.ceil(state.filtered.length / PAGE_SIZE)); const next = Math.max(1, Math.min(pages, state.page + direction)); if (next === state.page) return; state.page = next; renderCatalog(); document.querySelector('.catalog-bar').scrollIntoView({behavior:'smooth',block:'start'}); }; ui.prev.addEventListener('click', () => movePage(-1)); ui.next.addEventListener('click', () => movePage(1)); }
async function init() { bindEvents(); const finishLoading = startLoading('Cargando catálogo y tipos oficiales…'); try { const [catalog,types] = await Promise.all([fetchPokemonCatalog(),fetchTypes()]); state.catalog = catalog; state.filtered = catalog; catalog.forEach(entry => { state.byName.set(entry.name, entry); state.byId.set(getId(entry), entry); }); renderFilters(types); await renderCatalog(); } catch { showNotice('No pudimos cargar PokéAPI. Comprueba tu conexión y recarga la página.', true); } finally { finishLoading(); } }
init();
